### ISSUE TITLE
Project quota memory limit input error

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2302]
**Describe the bug**
1.Click Quota Management, click Edit Quota
2. Edit the memory limit, enter, and the Input greater than 8 fails

https://user-images.githubusercontent.com/88183150/134612952-6a65495b-1b05-4732-a78c-4f0388d5d0d5.mp4

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:v3.2.0-alpha.0

/kind bug
/@kubesphere/sig-console

**Comment by weili520** [comment]
this problem has been resolved. [fix: Resource limit input bug](https://github.com/kubesphere/console/pull/2268#issue-999971661)

**Comment by wenxin-01** [comment]
Hi @harrisonliu5 ,The issue remains in `nightly-20210928`
**How To Reproduce**
Steps to reproduce the behavior:
1、Click Quota Management，delete 'No request'
2、select ‘No request’
3、delete 'No request'
4、can not delete 'No request'

https://user-images.githubusercontent.com/68640256/135396394-7ed3ea96-9dbf-4e25-a77a-300adaffe282.mov

**Comment by weili520** [comment]
> Hi @harrisonliu5 ,The issue remains in `nightly-20210928` **How To Reproduce** Steps to reproduce the behavior: 1、Click Quota Management，delete 'No request' 2、select ‘No request’ 3、delete 'No request' 4、can not delete 'No request'
> 
>  2021-09-30.2.04.39.mov

get it.

**Comment by weili520** [comment]
@harrisonliu5
if we set the input number is 0, the component will replace it as text 'No Request', in addition the input component disallow input string value. I think there is no better way to solve it at now. How do you think about it?

**Comment by wenxin-01** [comment]
issue fixed in `nightly-20211021`
![image](https://user-images.githubusercontent.com/68640256/138387043-dd93bcdb-5944-4a19-bfe0-9e10e9892823.png)
