### ISSUE TITLE
Container startup probe is not showing

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2428]
**Describe the bug**
1. Add startup probe，click save,click to confirm 
2. View pod details，Startup probe not showing

![image](https://user-images.githubusercontent.com/88183150/136744523-74b2c7e5-e051-4674-a341-247dcba699be.png)

![image](https://user-images.githubusercontent.com/88183150/136744390-8c2fe620-8ca7-4369-8584-36f74579e3cf.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: nightly-20211010

**Expected behavior**
Startup probe information needs to be added behind the container terminal

/kind bug
/@kubesphere/sig-console
/priority medium

**Comment by harrisonliu5** [comment]
fixed by https://github.com/kubesphere/console/pull/2940

**Comment by jioce** [comment]
issue is not fixed
![image](https://user-images.githubusercontent.com/88183150/163749045-8226f599-3886-4ae7-8600-b9a76719685b.png)

![image](https://user-images.githubusercontent.com/88183150/163749093-44e70537-813d-469c-a403-06aa63b71799.png)

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/172309440-eabe469e-c123-497b-b393-f37db0af918e.png)

version used
kubesphere:  v3.3.0-rc.1
