### ISSUE TITLE
There is no way to change pipeline reviewer

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#961]
There is no way to change pipeline reviewer. So it is always project-admin.

![image](https://user-images.githubusercontent.com/22350668/88480171-e99a6b00-cf86-11ea-8dd7-5dec8944cde3.png)

![image](https://user-images.githubusercontent.com/22350668/88480185-05057600-cf87-11ea-91e9-5af289fae1e7.png)

**Comment by harrisonliu5** [comment]
fixed #963

/kind need-to-verify

**Comment by huanggze** [comment]
not fixed. new bug introduced

![image](https://user-images.githubusercontent.com/22350668/89141741-0c74e280-d578-11ea-8982-c88c6c71a421.png)

**Comment by huanggze** [comment]
verified
